title: Ver invest
remote_theme: "verinvest-pl/WhatATheme"
heroimage: /assets/img/hero.jpg
description: Empowering Fintech Futures, One Investment at a Time.

about: Ver Invest ASI sp. z o.o. jest wewnętrznie zarządzaną alternatywną spółką inwestycyjną utworzoną na podstawie ustawy o funduszach inwestycyjnych i zarządzaniu alternatywnymi funduszami inwestycyjnymi. Spółka wpisana jest do rejestru zarządzających alternatywnymi spółkami inwestycyjnymi prowadzonego przez Komisję Nadzoru Finansowego pod numerem PLZASI00359. Wyłącznym przedmiotem działalności ASI jest zbieranie aktywów od wielu inwestorów, w celu ich lokowania w interesie tych inwestorów. Celem inwestycyjnym ASI jest zwiększanie wartości jej aktywów poprzez wzrost łącznej wartości lokat oraz uzyskanie odsetek z lokat i innych przychodów z lokat. Cel inwestycyjny realizowany jest zgodnie z przyjętą polityką i strategią inwestycyjną. ASI nie gwarantuje osiągnięcia celów inwestycyjnych. Ver Invest ASI sp. z o.o. jako zarządzający ASI podlega nadzorowi Komisji Nadzoru Finansowego, która monitoruje wielkość aktywów ASI oraz kategorii lokat i rynków, na których inwestuje, w celu identyfikacji potencjalnych ryzyk systemowych, generowanych przez ogół zarządzających ASI.

author-image: /assets/img/avatar.jpg

authors:
  - image: https://verestro.com/uploads/media/images/0001/01/xthumb_178_images_small.jpeg.pagespeed.ic.3eH7J3nXbm.webp
    name: Krzysztof Drzyzga
    about: 'Krzysztof Drzyzga - Ponad 20 lat doświadczenia: w branży finansowej, płatności zdalne i zbliżeniowe, programy lojalnościowe, zarządzanie produktami, wspieranie rozwoju branży fintech, startupów i zarządzanie produktami. Odpowiedzialny za ogólną strategię i rozwój Verestro.'
  - image: https://verestro.com/uploads/media/images/0001/01/xthumb_85_images_small.jpeg.pagespeed.ic.Xy_gTCxq6c.webp
    name: Michał Maciąg
    about: 'Michał Maciąg - Z branżą płatniczą i fintech związany od 12 lat. Odpowiedzialny za dział IT i jego dynamiczny rozwój.'

address: ul.Promienna 10, 03-672 Warszawa
email: Ver-invest@verestro.com

portfolio: W trakcie przygotowania
